# Subject Names to their IDs
SUBJECTS_LB = {"Agriculture / Horticulture":"832","Active Leisure Studies":"848","Childcare / Community Care":"846","Crafts ; Design":"835","Engineering":"836","English And Communication":"810","French":"10","Gaeilge Chumarsaideach":"66","German":"11","Graphics And Construction Studies":"845","Hair And Beauty":"850","Hotel Catering; Tourism":"833","Information ; Communication Technology":"825","Italian":"13","Mathematic Applications":"830","Office Admin And Customer":"847","Sign Language":"816","Social Education":"815","Spanish":"12","Technology":"839"}

SUBJECTS_LC = {"Accounting":"32","Agricultural Economics":"26","Agricultural Science":"24","Ancient Greek":"7","Applied Mathematics":"20","Arabic":"59","Art":"14","Biology":"25","Bulgarian":"559","Business":"33","Chemistry":"22","Classical Studies":"8","Construction Studies":"29","Croatian":"567","Czech":"547","Danish":"38","Design & Communication Graphics":"562","Dutch":"17","Economics":"34","Engineering":"27","English":"2","Estonian":"552","Finnish":"49", "French":"10","Geography":"5","German":"11","Hebrew Studies":"9", "History Later Modern":"4","History Early Modern":"96","Home Economics S & S":"98","Hungarian":"551","Irish":"1","Italian":"13","Japanese":"58","Latin":"6","Latvian":"549","Link Modules":"462","Lithuanian":"550","Mathematics":"3","Modern Greek":"19","Music":"67","Physics":"21","Physics ; Chemistry":"23","Polish":"548","Portuguese":"18","Religious Education":"223","Romanian":"553","Russian":"99","Slovakian":"554","Spanish":"12","Swedish":"39","Technology":"65"}

SUBJECTS_JC = {"Ancient Greek":"7","Art Craft Design":"41","Business Studies":"42","Civic Social and Political Education":"218","Classical Studies":"8","English":"2","Environ & Social Studies":"81","French":"10","Geography":"5","German":"11","History Later Modern":"4","Home Economics":"52","Irish":"1","Italian":"13","Latin":"6","Material Technology (Wood)":"47","Mathematics":"3","Metalwork":"54","Music":"46","Religious Education":"220","Science":"57","Spanish":"12","Technical Graphics":"48","Technology":"65"}

EXAMINATION_SUBJECTS = {"lb": SUBJECTS_LB, "lc": SUBJECTS_LC, "jc": SUBJECTS_JC}

#Default POST Data

POST_DATA = {"MaterialArchive__noTable__cbv__AgreeCheck": "True", "MaterialArchive__noTable__cbh__AgreeCheck": "N", "MaterialArchive__noTable__sbh__ViewType": "id", "MaterialArchive__noTable__sbh__YearSelect": "id", "MaterialArchive__noTable__sbh__ExaminationSelect": "id", "MaterialArchive__noTable__sbh__SubjectSelect": "id"}
